In [ ]:
print "Hello World"

In [15]:
import numpy as np

https://towardsdatascience.com/getting-started-with-numpy-59b22df56729

In [ ]:
#Creating 1D array
a = np.array([1,2,3])

#Creating 2D array
b = np.array([[1,2,3],[4,5,6]])

print a
print b

In [ ]:
#Create Arrays
a = np.zeros((2,2)) #Create an array of all zeros

b = np.ones((1,2)) #Create an array of all ones

pi = 3.14

c = np.full((2,2),pi) #Create a constant array of pi

d = np.eye(3) #Create a 3x3 identity matrix

e = np.random.random((2,2)) #Create a random value matix

print 'a: \n', a, '\n'
print 'b: \n', b, '\n'
print 'c: \n', c, '\n'
print 'd: \n', d, '\n'
print 'e: \n', e, '\n'

In [ ]:
#Create Sequences

a = np.arange(0,30,5)

b = np.linspace(1,15,3)

print 'a: \n', a, '\n'
print 'b: \n', b, '\n'

In [ ]:
#Accessing Array Elements: Slicing

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

#Accessing an element
rowIndex = 0
colIndex = 2
b = a[rowIndex, colIndex]

print 'a: \n', a, '\n'
print 'b: \n', b, '\n'

startRowIndex = 1
endRowIndex = 3
startColIndex = 0
endColIndex = 3

c = a[startRowIndex:endRowIndex, startColIndex:endColIndex]

print 'c: \n', c, '\n'

In [23]:
#Basic Arithmatic Operations

#Create a dummy array for operations
a = np.array([1, 2, 5, 3])

print a, '\n'

#Add 3 to every element
a += 3

print a, '\n'

#Subtract 5 from every element
a -= 5

print a, '\n'

#Multiply each element by 7
a *= 7

print a, '\n'

#Divide each element by 6
a  /= 6

print a, '\n'

#Squaring each element
a **= 2

print a, '\n'

#Taking transpose
a = a.T

print a, '\n'

[1 2 5 3] 

[4 5 8 6] 

[-1  0  3  1] 

[-7  0 21  7] 

[-2  0  3  1] 

[4 0 9 1] 

[4 0 9 1] 

